name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    environment: PRO
    env:
      DATABASE_URL: "postgresql://testuser:testpass@localhost:5432/testdb?schema=public"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20.19.2
      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
      - run: pnpm install
      - run: pnpm exec prisma generate
      - run: pnpm exec prisma db push
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - name: Send Discord Notification
        run: |
          STATUS=${{ job.status }}
          COLOR=$([ "$STATUS" == "success" ] && echo "3066993" || echo "15158332")
          MESSAGE="**${{ github.repository }}** build *${STATUS}* on \`${{ github.ref_name }}\` by **${{ github.actor }}**"
          curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"embeds\":[{\"title\":\"CI Build $STATUS\",\"description\":\"$MESSAGE\",\"color\":$COLOR}]}" \
                ${{ secrets.DISCORD_WEBHOOK_URL }}
