name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    environment: PRO
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Notify Discord
        if: success()
        run: |
          VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          MESSAGE="🎉 **${{ github.repository }}** released **${VERSION}** by **${{ github.actor }}**"
          curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"embeds\":[{\"title\":\"New Release ${VERSION}\",\"description\":\"${MESSAGE}\",\"color\":3066993}]}" \
                ${{ secrets.DISCORD_WEBHOOK_URL }}
